// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByFBExt1gPrCKdcr_zTGbeSSgGXYweUoc',
    appId: '1:282587473930:web:c3ebedd888935a3c8d97f3',
    messagingSenderId: '282587473930',
    projectId: 'taleemconnect-994b1',
    authDomain: 'taleemconnect-994b1.firebaseapp.com',
    storageBucket: 'taleemconnect-994b1.firebasestorage.app',
    measurementId: 'G-VPN3XQL7GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTYkAWrm4Ibep1uFB458nAHrLdJ5W2LhI',
    appId: '1:282587473930:android:95342ca337adba628d97f3',
    messagingSenderId: '282587473930',
    projectId: 'taleemconnect-994b1',
    storageBucket: 'taleemconnect-994b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8BxTPtdcnjtYHyoJB0R7isF9J-I3y7Jo',
    appId: '1:282587473930:ios:2851dfc39d78e6b58d97f3',
    messagingSenderId: '282587473930',
    projectId: 'taleemconnect-994b1',
    storageBucket: 'taleemconnect-994b1.firebasestorage.app',
    androidClientId: '282587473930-1c9nod1epp51bpoejv6bl0jt5bv25sii.apps.googleusercontent.com',
    iosClientId: '282587473930-j1e49c9riv080i3tc7o29tqisv981aug.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8BxTPtdcnjtYHyoJB0R7isF9J-I3y7Jo',
    appId: '1:282587473930:ios:2851dfc39d78e6b58d97f3',
    messagingSenderId: '282587473930',
    projectId: 'taleemconnect-994b1',
    storageBucket: 'taleemconnect-994b1.firebasestorage.app',
    androidClientId: '282587473930-1c9nod1epp51bpoejv6bl0jt5bv25sii.apps.googleusercontent.com',
    iosClientId: '282587473930-j1e49c9riv080i3tc7o29tqisv981aug.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzG1kL46m_2MjtmHs6UT5gjFL8eTMn0oY',
    appId: '1:282587473930:web:000011f41c48a1d98d97f3',
    messagingSenderId: '282587473930',
    projectId: 'taleemconnect-994b1',
    authDomain: 'taleemconnect-994b1.firebaseapp.com',
    storageBucket: 'taleemconnect-994b1.firebasestorage.app',
    measurementId: 'G-7RBYTJTF79',
  );

}